#!/bin/bash
yum -y update

yum -y install httpd

yum -y install mariadb-server mariadb 

yum -y install php php-mysql php-gd php-pear php-mbstring

yum -y install firewalld


systemctl start firewalld && systemctl enable firewalld

firewall-cmd --permanent --add-service http && firewall-cmd --permanent --add-service https

sudo firewall-cmd --reload

systemctl start httpd && systemctl enable httpd

systemctl start mariadb && systemctl enable mariadb
