#!/bin/bash -xev 

yum -y update

yum -y install httpd

wait

yum -y install mariadb-server mariadb 

wait

yum -y install php php-mysql php-gd php-pear php-mbstring

wait

yum -y install firewalld


systemctl start firewalld && systemctl enable firewalld

firewall-cmd --permanent --add-service http && firewall-cmd --permanent --add-service https

sudo firewall-cmd --reload

systemctl start httpd && systemctl enable httpd

systemctl start mariadb && systemctl enable mariadb

exit 0
